language: ruby
sudo: false

rvm:
   - 2.0.0
   - 2.1.7
   - 2.2.3
   - 2.3.3

env:
  global:
  - PLUGIN=redmine_hourglass
  - REDMINE=test_redmine

  matrix:
  - REDMINE_VERSION=3.1.7 TRACE=--trace
  - REDMINE_VERSION=3.2.7 TRACE=--trace
  - REDMINE_VERSION=3.3.4 TRACE=--trace
  - REDMINE_VERSION=3.4.1 TRACE=--trace

before_install:
- . .travis/clone_redmine.sh
- gem install bundler

gemfile: test_redmine/Gemfile
install:
- cd $PATH_TO_REDMINE
- bundle install --jobs=3 --retry=3 --path=$PATH_TO_PLUGIN/vendor/bundle
- bundle exec rake $TRACE db:migrate
- bundle exec rake $TRACE redmine:load_default_data REDMINE_LANG=en
- bundle exec rake $TRACE $GENERATE_SECRET
- bundle exec rake $TRACE $MIGRATE_PLUGINS

script:
- cd $PATH_TO_REDMINE
- if [ "$TRACE" == "--trace" ]; then export BACKTRACE=--backtrace; fi
- if [ -z "$TRACE" ]; then unset BACKTRACE; fi
- bundle exec rspec $BACKTRACE --pattern $PATH_TO_PLUGIN/spec/**/*_spec.rb

cache:
  directories:
  - vendor/bundle
